### ISSUE TITLE
Needs default args

### ISSUE THREAD

**Issue by clarkmoody** [elcarim5efil/rollup-plugin-require-context#2]
The [args parser method](https://github.com/elcarim5efil/rollup-plugin-require-context/blob/master/src/generate_require_context_code.js#L4-L16) assumes all arguments are present. WebPack specifies defaults of `useSubdirectories = false, regExp = /^\.\//` for the second and third arguments.

The library should respect those defaults :-)

**Comment by elcarim5efil** [comment]
Thank you for your great advice. Changes are updated @1.0.0. Default args are added, checkout [resolve-require-modules](https://github.com/elcarim5efil/rollup-plugin-require-context/blob/master/src/helper/resolve-reqquire-modules.js#L26) or [test](https://github.com/elcarim5efil/rollup-plugin-require-context/blob/master/test/index.spec.js).

**Comment by clarkmoody** [comment]
👍
